### PR TITLE
Storage and lots of perf improvements

### PR DESCRIPTION
**Pull request by FroMage**
This is what we've been working on:

- New storage module to allow 3rd party libs to obtain ThreadLocal instances backed by custom thread fields
- Added FastThreadContextProvider that bypasses all custom ThreadContextProvider and just switches ThreadLocal
- Added FastStorageThreadContextProvider that does the same for ThreadLocal obtained by the new storage module
- Reworked all ThreadContext wrappers to store context directly inside their class depending on the number of contexts, to reduce allocations
- If there is a single ThreadContextProvider that doesn't support FAST paths, we revert to the MP-CP methods
- Do not wrap any lambda if the number of contexts to propagate/clear is empty

### CODE REVIEW

**Comment by geoand** [comment]
I'm reading through the code, but certainly don't wait on me to merge this if you feel it's ready

**Comment by FroMage** [comment]
Well, lots of tests are missing, but I don't have time to write them. I do feel the API is ready though. Perhaps I should add a way to disable the fast path with config or factory methods, just to be safe?

For the storage part, we can disable it in quarkus since it implements the `StorageManager`.

**Comment by geoand** [comment]
> Well, lots of tests are missing, but I don't have time to write them. I do feel the API is ready though. Perhaps I should add a way to disable the fast path with config or factory methods, just to be safe?
> 

Good idea.

As for the tests, I'll start looking into writing some soon

> For the storage part, we can disable it in quarkus since it implements the `StorageManager`.

👍🏼

**Comment by FroMage** [comment]
Added `boolean SRTC.isEmpty()` and `boolean SRTC.isContextualized(Object)` for Mutiny. Added `SRCM.Builder.enableFastThreadContextProvider(boolean)` to disable fast path.

**Comment by FroMage** [comment]
I'll just merge this and make a release so Mutiny can test/use this.

**Comment by manovotn** [comment]
Yea, I only had time to quick-scan it today, which for 70+ files wasn't enough for me to give it green.
But since you are confident, I think it's fine.

**Comment by FroMage** [comment]
Feel free to review it later and we'll address anything. But at least this allows Mutiny to progress with its PR.

**Pull request merged**
