### PR TITLE
GH Actions test

### PR DESCRIPTION
**Pull request by manovotn**
Do not merge.
This is just to test the CI after yesterday weird failures on release job.
For more context, see the failure here - https://github.com/smallrye/smallrye-context-propagation/runs/1729127280?check_suite_focus=true

### CODE REVIEW

**Review by geoand — DISMISSED** [review]
LGTM

**Comment by manovotn** [comment]
@geoand just ignore this PR for now :)
It's merely a CI check that I'm going to push few `echo`s into and do a few restarts just to see how GH actions reacts. Although it seems it isn't going to fail like it did for the release job which is a shame.

**Comment by manovotn** [comment]
@geoand now you can approve and merge it :)

I didn't manage to replicate the issue, but I've switched the order in which JDKs install which should make sure 12 is always set as home. Furthermore, I left the java home var setup in place along with echo just so that we can see what's being used if it ever fails again.

I've also updated the required java version in enforcer to 12 which is what we actually require.

**Review by geoand — APPROVED** [review]
LGTM!

**Pull request merged**
