### PR TITLE
Update to new config artifact/version scheme

### PR DESCRIPTION
**Pull request by kenfinnigan**

### CODE REVIEW

**Comment by manovotn** [comment]
Looks like you managed to freeze the build somehow, it works for me locally but the Semaphore is acting up and gives me empty build window

**Comment by kenfinnigan** [comment]
Yeah, I just restarted because it seemed hung

**Comment by manovotn** [comment]
I already did one restart before that. Didn't help...

**Comment by kenfinnigan** [comment]
seems to be running ok at present

**Comment by kenfinnigan** [comment]
woohoo!

**Pull request merged**
