### PR TITLE
New 1.0.20 release

### PR DESCRIPTION
**Pull request by FroMage**
I forgot to do a release for the JDK12 fix.

### CODE REVIEW

**Comment by FroMage** [comment]
@radcortez could you help us a bit here? It appears the github action for setting up JDK12 is failing, but I don't know if I messed up with CI config, or if we need to update our parent or something else?

**Comment by manovotn** [comment]
@FroMage this looks like error in our CI settings:
```
Error: Unable to process command '##[set-env name=JAVA_HOME;]/opt/hostedtoolcache/jdk/12.0.2/x64' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

And it's coming the the java setup GH action. It seems all you need to do is upgrade that. See [this])(https://github.com/actions/setup-java/issues/114) issue. Let me try and add a commit into this PR to see if that is indeed the issue.

**Comment by manovotn** [comment]
@FroMage JDK 12 build is green again.

But I wonder what is the CI step `build with JDK 11` that is not running and is marked as expected?
That is certainly not coming from our GH actions setup. @radcortez do you happen to know?

**Review by manovotn — APPROVED** [review]

**Comment by FroMage** [comment]
Thanks a lot @manovotn I wonder how we did not catch this in the JDK12 fix we merged.

I think this remaining error is just because CI is confused, I'll open another PR just to make sure.

**Pull request closed without merging**
